version: '3.2'
 
services:
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
   volumes:
     - elasticsearch_db:/usr/share/elasticsearch/data
     - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

   environment:
     ES_JAVA_OPTS: "-Xmx1g -Xms1g"
     ELASTIC_PASSWORD: elastic
   network_mode: "host"

 logstash:
   image: docker.elastic.co/logstash/logstash:7.17.3
   environment:
     LS_JAVA_OPTS: "-Xmx1g -Xms1g"
   volumes:
     - ./logstash.yml:/usr/share/logstash/config/logstash.yml
     - ./logstash.conf:/usr/share/logstash/config/logstash.conf
   network_mode: "host"
   depends_on:
     - elasticsearch

 kibana:
   image: docker.elastic.co/kibana/kibana:7.17.3
   volumes:
     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
   network_mode: "host"
   depends_on:
     - elasticsearch

volumes:
 elasticsearch_db:
